spring.application.name=smartglass
server.port=50500

# Configuración MySQL (Usuarios y Transacciones)
spring.datasource.url=jdbc:mysql://localhost:3306/smartglass_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración MongoDB (Catálogo y Carrito)
spring.data.mongodb.uri=mongodb://localhost:27017/smartglass_catalog

# Configuración de Seguridad JWT
smartglass.jwt.secret=ClaveSecretaSuperSeguraParaSmartGlass2026ConSuficientesBitsParaHMACSHA256
smartglass.jwt.expiration-ms=86400000

# --- SEGURIDAD DE COOKIES Gestión de sesiones ---
server.servlet.session.cookie.name=SMARTGLASS_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false

# --- TIEMPOS DE SESIÓN ---

server.servlet.session.timeout=15m
server.servlet.session.cookie.max-age=900

# --- CONTROL DE ERRORES ---

server.error.include-message=always
server.error.whitelabel.enabled=false

# Mostrar errores detallados de seguridad en la terminal
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# ===============================
# CONFIGURACIÓN OAUTH2 (GOOGLE LOGIN)
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:50500/login/oauth2/code/google
